"""migrate the messages to a database

Revision ID: 1794464bcfa5
Revises: 
Create Date: 2023-10-26 12:18:33.434916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1794464bcfa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_data')
    # ### end Alembic commands ###
